# Generated by Django 5.0.6 on 2024-07-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_message', models.TextField(max_length=255)),
                ('doctor_response', models.TextField(max_length=255)),
            ],
        ),
    ]
