# Generated by Django 5.0.6 on 2024-07-11 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='next_action',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='doctor_response',
            field=models.TextField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='patient_message',
            field=models.TextField(default='null', max_length=255),
        ),
    ]
