# Generated by Django 5.0.6 on 2024-07-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=255)),
                ('data_id', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('x', models.CharField(max_length=255)),
                ('y', models.CharField(max_length=255)),
                ('table_data', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
    ]
