# Generated by Django 5.0.6 on 2024-07-02 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capturing_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacapture',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='datacapture',
            name='next_action',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='datacapture',
            name='upload_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
