# Generated by Django 5.0.6 on 2024-07-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capturing_system', '0002_datacapture_file_name_datacapture_next_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacapture',
            name='data',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='data_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='table_data',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='width',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='x',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='y',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
