# Generated by Django 5.0.6 on 2024-07-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capturing_system', '0003_alter_datacapture_data_alter_datacapture_data_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacapture',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='width',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
