# Generated by Django 5.0.6 on 2024-07-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capturing_system', '0004_alter_datacapture_height_alter_datacapture_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacapture',
            name='data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='data_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='invoice_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='table_data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='x',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datacapture',
            name='y',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
