# Generated by Django 5.0.6 on 2024-05-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_lines_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
    ]
