# Generated by Django 5.0.6 on 2024-05-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_lines_table', '0002_alter_material_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='product_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
