# Generated by Django 5.0.6 on 2024-06-24 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecast_products', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductForecastStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_of_product', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast_products.product')),
            ],
        ),
    ]
