# Generated by Django 5.0.6 on 2024-06-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_products', '0002_alter_product_product_id'),
        ('stage_of_product_forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productforecaststage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast_products.product', to_field='product_id'),
        ),
    ]
