# Generated by Django 5.0.6 on 2024-06-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_of_product_forecast', '0002_alter_productforecaststage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productforecaststage',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productforecaststage',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
