# Generated by Django 5.0.4 on 2024-07-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage_of_product_forecast', '0004_productforecaststage_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productforecaststage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='productforecaststage',
            name='stage_of_product',
        ),
        migrations.RemoveField(
            model_name='productforecaststage',
            name='start_date',
        ),
    ]
