# Generated by Django 5.0.6 on 2024-07-10 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_of_product_forecast', '0005_remove_productforecaststage_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productforecaststage',
            old_name='next_stage',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='productforecaststage',
            old_name='previous_stage',
            new_name='product_stage',
        ),
        migrations.RemoveField(
            model_name='productforecaststage',
            name='next_duration',
        ),
        migrations.AddField(
            model_name='productforecaststage',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
