# Generated by Django 5.0.6 on 2024-07-12 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_of_product_forecast', '0006_rename_next_stage_productforecaststage_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productforecaststage',
            old_name='product_name',
            new_name='operation',
        ),
        migrations.RenameField(
            model_name='productforecaststage',
            old_name='product_stage',
            new_name='production_order_type',
        ),
        migrations.AddField(
            model_name='productforecaststage',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='productforecaststage',
            name='operation_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productforecaststage',
            name='production_order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productforecaststage',
            name='resident',
            field=models.IntegerField(default=0),
        ),
    ]
