# Generated by Django 5.0.4 on 2024-05-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_value', models.CharField(max_length=100)),
                ('updated_date_and_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
